### ISSUE TITLE
Install eror caused by failed to select a version for the requirement `zeroize = "^0.9"`

### ISSUE THREAD

**Issue by Goosie** [pandoracore/bitcoin-pro#17]
I got an error after installing bitcoin-pro while following the instructions in the readme.
After the command: cargo install bitcoin-pro
I got:
error: failed to compile `bitcoin-pro v0.1.0`, intermediate artifacts can be found at `/tmp/cargo-installD5taeA`

Caused by:
  failed to select a version for the requirement `zeroize = "^0.9"`
  candidate versions found which didn't match: 1.3.0, 1.2.0, 1.1.1, ...
  location searched: crates.io index
  required by package `grin_secp256k1zkp v0.7.10`
      ... which is depended on by `rgb-core v0.4.0`
      ... which is depended on by `bitcoin-pro v0.1.0`

**Comment by Goosie** [comment]
Seems the same error as https://github.com/pandoracore/bitcoin-pro/issues/16

**Comment by Goosie** [comment]
Is there a workaround for this error?

**Comment by dr-orlovsky** [comment]
Yes, that's a duplicate of #16. Grin has released fixed version of their library so I will do a minor release now and it should be working. Will let you know here

**Comment by Goosie** [comment]
Yess, working now :-) Thanks!

**Comment by dr-orlovsky** [comment]
Did `v0.1.1` release as well

**Comment by Goosie** [comment]
Checked out and is working.
