### ISSUE TITLE
Failed to build - error[E0412]: cannot find type `NoneError` in module `std::option`

### ISSUE THREAD

**Issue by chokoboko** [pandoracore/bitcoin-pro#18]
Hi, I'm facing the following error when building: 
```
   Compiling glade v0.1.0-alpha.4
error[E0412]: cannot find type `NoneError` in module `std::option`
  --> /Users/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/glade-0.1.0-alpha.4/src/error.rs:22:25
   |
22 |     #[from(std::option::NoneError)]
   |                         ^^^^^^^^^ not found in `std::option`
```

MacOS 10.14.6 Mojave
rustc 1.54.0-nightly (9111b8ae9 2021-05-26)

**Comment by chokoboko** [comment]
Found this recently merged PR: https://github.com/rust-lang/rust/pull/85482

**Comment by UkolovaOlga** [comment]
Thank you! Will look into it and give you an update soon

**Comment by UrsZeidler** [comment]
I have the same problem in a fresh ubuntu 20.04.
I switched to another nightly build of rust, `rustup toolchain install nightly-2021-05-16` which worked.

**Comment by dr-orlovsky** [comment]
Yes, Bitcoin Pro currently requires nightly version
