### ISSUE TITLE
Install Unbuntu 18.04 failed

### ISSUE THREAD

**Issue by henkvancann** [pandoracore/bitcoin-pro#4]
The cargo install command failed. Any ideas what to do next?

   Compiling glade v0.1.0-alpha.2
error[E0554]: `#![feature]` may not be used on the stable release channel
  --> /home/hvancann/.cargo/registry/src/github.com-1ecc6299db9ec823/glade-0.1.0-alpha.2/src/lib.rs:15:1
   |
15 | #![feature(try_trait)]
   | ^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

For more information about this error, try `rustc --explain E0554`.
error: could not compile `glade`.

**Comment by dr-orlovsky** [comment]
As error suggests says, you just need to compile with rust nightly. Install it with `rustup install nightly` and use with `rustup default nightly`

**Comment by henkvancann** [comment]
Thx, I report my experience here: https://github.com/henkvancann/bitcoin-pro/blob/master/doc/trouble-shooting.md When we have it working I'll offer you a PR.

Back to trouble :) 

Now the build process drops out even earlier:
   **Compiling futures v0.3.8**

error: failed to run custom build command for `glib-sys v0.10.1`

Caused by:
  process didn't exit successfully: `/tmp/cargo-install2sx0or/release/build/glib-sys-ba736a28d8619eda/build-script-build` (exit code: 1)
--- stdout
cargo:rerun-if-env-changed=GLIB_2.0_NO_PKG_CONFIG
cargo:rerun-if-env-changed=PKG_CONFIG
cargo:rerun-if-env-changed=GLIB_2.0_STATIC
cargo:rerun-if-env-changed=GLIB_2.0_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_STATIC
cargo:rerun-if-env-changed=PKG_CONFIG_ALL_DYNAMIC
cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_PATH_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_PATH
cargo:rerun-if-env-changed=PKG_CONFIG_PATH
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_LIBDIR
cargo:rerun-if-env-changed=PKG_CONFIG_LIBDIR
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-gnu
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_gnu
cargo:rerun-if-env-changed=HOST_PKG_CONFIG_SYSROOT_DIR
cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR

--- stderr
`"pkg-config" "--libs" "--cflags" "glib-2.0" "glib-2.0 >= 2.64"` did not exit successfully: exit code: 1
--- stderr
Requested 'glib-2.0 >= 2.64' but version of GLib is 2.56.4


warning: build failed, waiting for other jobs to finish...
error: failed to compile `bitcoin-pro v0.1.0-beta.1`, intermediate artifacts can be found at `/tmp/cargo-install2sx0or`

Caused by:
  build failed

**Comment by dr-orlovsky** [comment]
Have you performed this command from README?

```console
$ sudo apt update
$ sudo apt install -y cargo libssl-dev libzmq3-dev pkg-config g++ cmake libgtk-3-dev libsqlite3-dev
```

In particular, you need to have `libgtk-3-dev` installed

**Comment by henkvancann** [comment]
Yep, I followed the howto
  

  

  

  
  
  
  
  
>

**Comment by henkvancann** [comment]
Went through the whole process on Ubuntu 18.04 again. Keep getting the error message this issue started with. I'll get back when the installation process + documentation is more mature for rust - noobs like me :)

**Comment by stefan52a** [comment]
Juts FYI: bitcoin-pro seemed to install fine under Windows WSL2 Ubuntu 20.04

**Comment by Goosie** [comment]
Bitcoin-pro is installing nicely under Ubuntu 20.04 indeed.
