### ISSUE TITLE
Install Ubuntu 20.04 failed

### ISSUE THREAD

**Issue by Goosie** [pandoracore/bitcoin-pro#7]
Trying to install bitcoin-pro, followed the instructions as mentioned:
sudo apt update (did even sudo apt upghrade)
sudo apt install -y cargo libssl-dev libzmq3-dev pkg-config g++ cmake libgtk-3-dev libsqlite3-dev
rustup install nightly

I get    Compiling diesel_derives v1.4.1
error[E0432]: unresolved import `syn::export`
  --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/amplify_derive-2.3.1/src/as_any.rs:16:10
   |
16 | use syn::export::TokenStream2;
   |          ^^^^^^ could not find `export` in `syn`

error[E0432]: unresolved import `syn::export`
  --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/amplify_derive-2.3.1/src/display.rs:17:10
   |
17 | use syn::export::{Span, TokenStream2};
   |          ^^^^^^ could not find `export` in `syn`

error[E0432]: unresolved import `syn::export`
  --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/amplify_derive-2.3.1/src/error.rs:17:10
   |
17 | use syn::export::TokenStream2;
   |          ^^^^^^ could not find `export` in `syn`

error[E0432]: unresolved import `syn::export`
  --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/amplify_derive-2.3.1/src/from.rs:17:10
   |
17 | use syn::export::{Span, TokenStream2};
   |          ^^^^^^ could not find `export` in `syn`

error[E0432]: unresolved import `syn::export`
  --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/amplify_derive-2.3.1/src/getters.rs:16:10
   |
16 | use syn::export::TokenStream2;
   |          ^^^^^^ could not find `export` in `syn`

error[E0432]: unresolved import `syn::export`
  --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/amplify_derive-2.3.1/src/wrapper.rs:16:10
   |
16 | use syn::export::{TokenStream2};
   |          ^^^^^^ could not find `export` in `syn`

error[E0432]: unresolved import `syn::export`
  --> /home/perry/.cargo/registry/src/github.com-1ecc6299db9ec823/amplify_derive-2.3.1/src/lib.rs:67:10
   |
67 | use syn::export::TokenStream;
   |          ^^^^^^ could not find `export` in `syn`

error: aborting due to 7 previous errors

For more information about this error, try `rustc --explain E0432`.
error: could not compile `amplify_derive`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `bitcoin-pro v0.1.0-beta.1`, intermediate artifacts can be found at `/tmp/cargo-installocOWj4`

Caused by:
  build failed

**Comment by Goosie** [comment]
Even removed the bitcoin-pro, cloned again an tried again, error keeps comming.

**Comment by Goosie** [comment]
In the tmp directory I found a file .rustc_info.json which gave as -Csplit-debiginfo is instable on the platform.

{"rustc_fingerprint":3332057247248665783,"outputs":{"4476964694761187371":{"success":true,"status":"","code":0,"stdout":"___\nlib___.rlib\nlib___.so\nlib___.so\nlib___.a\nlib___.so\n/home/perry/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu\ndebug_assertions\npanic=\"unwind\"\nproc_macro\ntarget_arch=\"x86_64\"\ntarget_endian=\"little\"\ntarget_env=\"gnu\"\ntarget_family=\"unix\"\ntarget_feature=\"fxsr\"\ntarget_feature=\"sse\"\ntarget_feature=\"sse2\"\ntarget_has_atomic=\"16\"\ntarget_has_atomic=\"32\"\ntarget_has_atomic=\"64\"\ntarget_has_atomic=\"8\"\ntarget_has_atomic=\"ptr\"\ntarget_has_atomic_equal_alignment=\"16\"\ntarget_has_atomic_equal_alignment=\"32\"\ntarget_has_atomic_equal_alignment=\"64\"\ntarget_has_atomic_equal_alignment=\"8\"\ntarget_has_atomic_equal_alignment=\"ptr\"\ntarget_has_atomic_load_store=\"16\"\ntarget_has_atomic_load_store=\"32\"\ntarget_has_atomic_load_store=\"64\"\ntarget_has_atomic_load_store=\"8\"\ntarget_has_atomic_load_store=\"ptr\"\ntarget_os=\"linux\"\ntarget_pointer_width=\"64\"\ntarget_thread_local\ntarget_vendor=\"unknown\"\nunix\n","stderr":""},"1164083562126845933":{"success":true,"status":"","code":0,"stdout":"rustc 1.52.0-nightly (fe1bf8e05 2021-02-23)\nbinary: rustc\ncommit-hash: fe1bf8e05c39bdcc73fc09e246b7209444e389bc\ncommit-date: 2021-02-23\nhost: x86_64-unknown-linux-gnu\nrelease: 1.52.0-nightly\nLLVM version: 11.0.1\n","stderr":""},"551384519178316037":{"success":false,"status":"exit code: 1","code":1,"stdout":"","stderr":"error: `-Csplit-debuginfo` is unstable on this platform\n\n"}},"successes":{}}

**Comment by Goosie** [comment]
Tried also:
$ cargo build (which gave no errors) but did not start the application after the command bitcoin-pro
Luck shot by doing cargo install bitcoin-pro --version 0.1.0-beta.2 (did not work)
![error bitcoin-pro](https://user-images.githubusercontent.com/176074/108993229-8e566580-769a-11eb-94dd-c72fd980e2e8.png)

**Comment by Goosie** [comment]
Tried to install it on laptop with Linux Mint, got the same errors.

**Comment by dr-orlovsky** [comment]
Your error is caused by the fact that `cargo` picks older `amplify-derive` version, which had a dependency that not followed semantic version upgrade policy.

Rust cargo sometimes making me mad. It does compile with the current `Cargo.lock` file. Nevertheless I did a `cargo update` and just pushed it as a new commit (it still compiles).  Please try the following (inside the repo dir):
```
git checkout master
git pull origin
cargo clean
cargo update
cargo build
```

**Comment by Goosie** [comment]
Thanks,
The following commands worked out without errors.:
git checkout master
git pull origin
cargo clean
cargo update
cargo build --all-features

Unfortunately the command bitcoin-pro did not work. I find the commando by running the command ./bitcoin-pro in the /target/debug directory. I will create a shortcut for this part Now it's working

**Comment by dr-orlovsky** [comment]
I plan to do a macOS and Debian distribution package with proper shortcuts & icons — just need a bit more time for finishing it

**Comment by Goosie** [comment]
Thanks for the great work. Realy exciting. Let me know, I will help with testing.
